ORM Example #1
lovetosleep/testExample pull request #10
Opened 2018-05-22 13:11 UTC by lovetosleep

2018-05-22 18:25 UTC, troepolik requested changes

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/Model/Car.cs
>      class Car : IIntegerKey
у хибера есть особенность- для нормальной работы кэшей. объект должен оверрайдить методы
public override bool Equals(object obj)
public override int GetHashCode()
иначе они долго работают т.к сравнивают полное содержимое объекта, а не только id
помоему это даже в документации у них мелькает, во всяком случае раньше.

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/Model/CarTypeModel.cs
> +    class CarTypeModel
class CarTypeModel
я не очень понял для чего одновременно и Id  и  Type  это же вроде одно и тоже...
возможно ты это сделал чтобы пользовать enum.
но там кажется таких огранечений нет и ты можешь сделать public virtual CarType Id { get; set; }

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/NHibernate/Car.hbm.xml
> +  <class name="Car" table="AutoConfig">
<class name="Car" table="AutoConfig">
напишу на всякий случай- у хибера есть более удобные способы задания маппингов и конфигурации- через атрибуты, Fluent , и еще какой-то Code  - типа Fluent  только в чем -то там еще упрощение, не помню.

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/NHibernate/CarTypeEnumStringType.cs
> +    class CarTypeEnumStringType : EnumStringType
class CarTypeEnumStringType : EnumStringType
что-то странное... ты бы писал комменты над классами, я что-то не вдупляю зачем это...

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +                        CarCollection = new ObservableCollection<CarViewModel>(CarCollection.Take(counOfNoChangeItems));
CarCollection = new ObservableCollection<CarViewModel>(CarCollection.Take(counOfNoChangeItems));
что-то вообще не понял смысла происходящего)

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/BaseRepository.cs
> +            session.Save(obj);
session.Save(obj);
а это работает если объект уже не новый?

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/CachedRepositary.cs
> +                loaclObject = base.Load().Where(item => item.Id == id).FirstOrDefault();
loaclObject = base.Load().Where(item => item.Id == id).FirstOrDefault();
не слишком ли жирно грузить всю таблицу из базы, а потом выгребать по ид? у репозитория должнен быть метод 
GetByKey  и GetByLinq да и по sql  тоже не мешает. хибер умеет все 3 варианта выполнять
кстати, Where(item => item.Id == id).FirstOrDefault();- это излишество. можно писать так : .FirstOrDefault(item => item.Id == id);

2018-05-22 18:25 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/CachedRepositary.cs
> +            foreach (T value in base.Load())
foreach (T value in base.Load())
return base.Load();
что-то мне непонятен этот оверхед...

2018-05-22 20:17 UTC, lovetosleep commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/CachedRepositary.cs
> +            foreach (T value in base.Load())
тут тоже самое же, что и было в кэш репе, только Sql - запрос убрал, выгружает то из базы все данные и sql-запросов не нужно. Как я понял. Ну и помещает все данные в кэш.

2018-05-22 20:22 UTC, lovetosleep commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/BaseRepository.cs
> +            session.Save(obj);
Да работает, он его перезаписывает, если во ViewModel я передам объект который есть в базе,  то он просто добавит изменения, хотя есть метод Update для таких случаев, может его добавить ?

2018-05-22 20:25 UTC, lovetosleep commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +                        CarCollection = new ObservableCollection<CarViewModel>(CarCollection.Take(counOfNoChangeItems));
Это для удаления изменений на форме. К примеру у меня 5 объектов из базы выгрузились, я добавил новый в коллекцию, но не сохранил в БД. counOfNoChangeItems - содержит кол-во элементов сохраненных в БД записей(в методе Save это поле обновляется), и если я хочу сбросить изменения на форме, то все не сохраненные в БД записи скипаются и коллекция возвращается ко всем сохраненным записям.

2018-05-22 20:29 UTC, lovetosleep commented on AutoProjectWPF/AutoProjectWPF/NHibernate/CarTypeEnumStringType.cs
> +    class CarTypeEnumStringType : EnumStringType
В этом моменты у меня была проблема считывания из БД enum полей, в БД у меня CarTypeId -  в виде чисел представлен, ключ ссылающийся на другую таблицу с названиями типов. Посмотрел решение проблемы, нужно добавить данный класс-конвертер, как я понял.

2018-05-22 20:30 UTC, lovetosleep commented on AutoProjectWPF/AutoProjectWPF/NHibernate/Car.hbm.xml
> +  <class name="Car" table="AutoConfig">
Да, видел подобные реализации, хотел у вас спросить, что лучше использовать. Мне приглянулся этот метод решения, что-бы не писать кучу кода. Но не знаю лучшее ли это решение или нет.

2018-05-22 20:32 UTC, lovetosleep commented on AutoProjectWPF/AutoProjectWPF/Model/CarTypeModel.cs
> +    class CarTypeModel
Этот класс я сделал, для считывания второй таблицы из БД, как модель данных, далее я просто его закидываю в CarTypeViewModel, что бы пользователю показать "человеческие" типы моих машин.

2018-05-24 17:39 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/Model/CarTypeModel.cs
> +    class CarTypeModel
это я как раз понял. смотри Car и CarType связанные таблицы.
т.е должно быть так: Car.CarType = CarType.Id
и соотв-но непонятно зачем в таблице CarType  еще одно поле CarType...

2018-05-24 17:43 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/NHibernate/Car.hbm.xml
> +  <class name="Car" table="AutoConfig">
хмл  самый ранний способ. и чем он неудобен- нет интелисенс, какой-то типизированности... можно поменять тип поля и забыть поменять его в хмл . но я впринципе не настаиваю чтобы ты переделывал.

2018-05-24 17:47 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/NHibernate/CarTypeEnumStringType.cs
> +    class CarTypeEnumStringType : EnumStringType
что-то мне подсказывает что можно и без конверетера, просто указать полный тип этого enum  и чтобы enum  от int  наследовался. во всяком случае у нас так работает. но мы задаем маппинг через атрибуты, что впрочем не так удобно как Fluent  например.
так что попробуй указать просто полный тип. мб получится
впрочем это поле в этой таблице - это оверхэд. не нужно оно тебе тут. достаточно id

2018-05-24 17:49 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +                        CarCollection = new ObservableCollection<CarViewModel>(CarCollection.Take(counOfNoChangeItems));
в задании подразумевалось что можно скидывать изменения не только новых, но и ранее сохраненных. т.е открыл, поменял что-то в существующем, передумал, откатил.

2018-05-24 17:50 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/BaseRepository.cs
> +            session.Save(obj);
хибер вообще в этом плане путанный. у него еще и SaveOrUpdate есть)  можно впринципе в документации читануть в чем отличия.

2018-05-24 17:58 UTC, troepolik requested changes

2018-05-24 17:58 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/CachedRepositary.cs
> +            T localObject = session.Query<T>().FirstOrDefault(predicate);
public T GetByLinq(Func<T, bool> predicate)
+        {
+            T localObject = session.Query<T>().FirstOrDefault(predicate);
GetByLinq  предполагает возрат нескольких объектов, не обязательно одного.
и почему этот метод не в базовом классе? такая штука по идее должна быть не только с поддержкой кэша...

2018-05-24 17:58 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/CachedRepositary.cs
> +        public IList<T> GetByQuery(string query)
public IList<T> GetByQuery(string query)
подобные методы должны быть в базовом классе.

2018-05-24 17:58 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/CachedRepositary.cs
>          public override List<T> Load()
// Немного изменил, а то два раза выгрузка данных получается.
         public override List<T> Load()
на будущее: в шарпе коментарии на методом, полем, классом пишутся так: ставишь /// и студия добавляет разметку для комента. этот коммент будет виден в интелисенсе. но так пишут комменты говорящие что это за метод и что он делает.

2018-05-29 19:17 UTC, troepolik requested changes
В целом неплохо. серьезных нареканий нет, но в будущем тебе такие конструкции наделают проблем. так что лучше подчистить, упростить как сказано в комментах

2018-05-29 19:17 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +            CarRepo = new CachedRepositary<Car>();
CarRepo = new CachedRepositary<Car>();
+            CarTypeRepo = new BaseRepository<CarTypeModel>();
+            LoadingRecordsRepo = new BaseRepository<Car>();
не ошибка, но вдруг ты не знаешь. создание объектов,  можно делать прямо на уровне их объявления в классе. это равносильно прописыванию их в конструкторе.

2018-05-29 19:17 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
>          public ActionViewModel SaveItem
public ActionViewModel SaveItem
такое себе предприятие для юзера- кликать сначала Apply,  а потом Save
вообще ты усложнил себе жизнь и задание, я имел ввиду откат изменений на форме текущего редактируемого объекта и соотв-но сохраняем мы всегда текущий...
в итоге у тебя получилась весьма громоздкая реализация с различными переменными... типа counOfNoChangeItems, потенциальными багами при удалении из середины,  жестким ограничением на то что никто ничего не вставляет в середину. упрости все это. сохраняем только текущий, откатываем изменения только в текущем.

2018-05-29 19:17 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +                        catch (NullReferenceException e)
catch (NullReferenceException e)
+                        {
+                            MessageBox.Show("Не выбран сохраняемый объект. \n" + e.Message, "Ошибка выбора данных", MessageBoxButton.OK, MessageBoxImage.Warning);
+                        }
имей ввиду что чаще всего логичнее и сделать проверку на соответствие логике чем ловить эксепшены.
т.к например NullReferenceException  может выпасть еще где-нить ...
еще следует иметь ввиду что все непойманные исключения пойдут в UI-  поток ,что уронит твое приложение.

2018-05-29 19:17 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +                            foreach (CarViewModel item in CarCollection.Skip(counOfNoChangeItems))
foreach (CarViewModel item in CarCollection.Skip(counOfNoChangeItems))
вместо всей этой заморочки мог сделать один цикл с проверкой на положительность Id
новые элементы имеют <=0  положительные id  генерятся при сохранении. распространенная практика.

2018-05-29 19:17 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/MainViewModel.cs
> +                        for (int i = 0; i < CarCollection.Count; i++)
for (int i = 0; i < CarCollection.Count; i++)
алгоритмически здесь ошибка в том что внешний цикл нахрен не нужен. тебе достаточно перебрать внутренний- пройтись по измененным ид,если они есть, достать их из базы и потом подложить в коллекцию
ну а если в будущем нужно будет что-то подобное то частенько юзается такая конструкция
var findL = List1.Where(item=>list2.Contains(item.id))

2018-05-29 19:17 UTC, troepolik commented on AutoProjectWPF/AutoProjectWPF/ViewModel/Repositories/BaseRepository.cs
> +                using (var transaction = session.BeginTransaction())
на кой тут транзакция не понятно...

2018-05-31 19:09 UTC, troepolik approved these changes

2018-05-31 19:09 UTC, merged